# Generated by Django 3.2.16 on 2022-12-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_likearticle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesarticle', to='article.article'),
        ),
    ]
