# Generated by Django 3.2.16 on 2023-01-12 01:38

import article.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='blank-profile.webp', upload_to=article.utils.profile_pic_path),
        ),
    ]
